# Generated by Django 5.2.17 on 2026-09-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=40, verbose_name='租客')),
                ('landlord_name', models.CharField(max_length=40, verbose_name='房东')),
                ('rent', models.PositiveIntegerField(verbose_name='月租（元）')),
                ('deposit', models.PositiveIntegerField(default=0, verbose_name='押金（元）')),
                ('start_date', models.DateField(verbose_name='租期开始')),
                ('end_date', models.DateField(verbose_name='租期结束')),
                ('status', models.CharField(choices=[('有效', '有效'), ('已续租', '已续租'), ('已到期', '已到期'), ('已退租', '已退租')], default='有效', max_length=12, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property')),
                ('renewed_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_contract', to='contract.contract', verbose_name='续租生成的新合同')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=40, verbose_name='租客')),
                ('landlord_name', models.CharField(max_length=40, verbose_name='房东')),
                ('new_start_date', models.DateField(verbose_name='新租期开始')),
                ('new_end_date', models.DateField(verbose_name='新租期结束')),
                ('proposed_rent', models.PositiveIntegerField(verbose_name='期望月租（元）')),
                ('current_rent', models.PositiveIntegerField(verbose_name='发起时月租（元）')),
                ('status', models.CharField(choices=[('待房东处理', '待房东处理'), ('待租客确认', '待租客确认'), ('已续租', '已续租'), ('已取消', '已取消')], default='待房东处理', max_length=12, verbose_name='状态')),
                ('message', models.CharField(blank=True, default='', max_length=200, verbose_name='附言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='contract.contract', verbose_name='原合同')),
                ('created_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_renewal', to='contract.contract', verbose_name='续租成功后生成的新合同')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='properties.property', verbose_name='房源')),
            ],
            options={
                'verbose_name': '续租协商',
                'verbose_name_plural': '续租协商',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenewalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('租客', '租客'), ('房东', '房东')], max_length=12, verbose_name='处理人角色')),
                ('actor_name', models.CharField(max_length=40, verbose_name='处理人')),
                ('action', models.CharField(max_length=20, verbose_name='动作')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('renewal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contract.renewalrequest')),
            ],
            options={
                'verbose_name': '续租处理记录',
                'verbose_name_plural': '续租处理记录',
                'ordering': ['created_at'],
            },
        ),
    ]
