# Generated by Django 5.1.15 on 2026-09-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=40, verbose_name='租客姓名')),
                ('landlord_name', models.CharField(max_length=40, verbose_name='房东姓名')),
                ('rent', models.IntegerField(verbose_name='月租（元）')),
                ('start_date', models.DateField(verbose_name='租期开始')),
                ('end_date', models.DateField(verbose_name='租期结束')),
                ('status', models.CharField(default='生效中', max_length=20, verbose_name='合同状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.property')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_contracts', to='contract.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='期望新租期开始')),
                ('end_date', models.DateField(verbose_name='期望新租期结束')),
                ('rent', models.IntegerField(verbose_name='当前协商月租（元）')),
                ('expected_rent', models.IntegerField(verbose_name='租客发起时的期望月租（元）')),
                ('status', models.CharField(default='待房东处理', max_length=20, verbose_name='协商状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contract.contract')),
                ('new_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_sources', to='contract.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenewalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=20, verbose_name='处理角色')),
                ('action', models.CharField(default='发起续租', max_length=20, verbose_name='处理动作')),
                ('rent', models.IntegerField(blank=True, null=True, verbose_name='本次处理涉及的月租')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('renewal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contract.renewal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
