HOUSE_STATUS = ('待出租', '已预约', '已签约')
REPAIR_TYPES = ('水电', '门锁', '管道', '家电', '其他')
USER_ROLES = ('房东', '租客', '物业人员')

# 角色
ROLE_LANDLORD = '房东'
ROLE_TENANT = '租客'

# 合同状态：已续租/已到期的合同不再参与租期重叠判断，也不能再次更改
CONTRACT_STATUS_ACTIVE = '有效'
CONTRACT_STATUS_RENEWED = '已续租'
CONTRACT_STATUS_EXPIRED = '已到期'
CONTRACT_STATUS_TERMINATED = '已退租'
CONTRACT_STATUSES = (
    CONTRACT_STATUS_ACTIVE,
    CONTRACT_STATUS_RENEWED,
    CONTRACT_STATUS_EXPIRED,
    CONTRACT_STATUS_TERMINATED,
)
# 会占用房源租期的合同状态
CONTRACT_OCCUPYING_STATUSES = (CONTRACT_STATUS_ACTIVE,)

# 续租协商状态
RENEWAL_STATUS_PENDING_LANDLORD = '待房东处理'
RENEWAL_STATUS_PENDING_TENANT = '待租客确认'
RENEWAL_STATUS_RENEWED = '已续租'
RENEWAL_STATUS_CANCELLED = '已取消'
RENEWAL_STATUSES = (
    RENEWAL_STATUS_PENDING_LANDLORD,
    RENEWAL_STATUS_PENDING_TENANT,
    RENEWAL_STATUS_RENEWED,
    RENEWAL_STATUS_CANCELLED,
)
# 终态：进入后不再允许任何更改
RENEWAL_FINAL_STATUSES = (RENEWAL_STATUS_RENEWED, RENEWAL_STATUS_CANCELLED)
