HOUSE_STATUS = ('待出租', '已预约', '已签约')
REPAIR_TYPES = ('水电', '门锁', '管道', '家电', '其他')
USER_ROLES = ('房东', '租客', '物业人员')

# 续租协商中的角色
LANDLORD_ROLE = '房东'
TENANT_ROLE = '租客'

# 合同状态
CONTRACT_STATUS_ACTIVE = '生效中'
CONTRACT_STATUS_EXPIRED = '已到期'
CONTRACT_STATUS_RENEWED = '已续租'
CONTRACT_STATUS_CANCELED = '已取消'
CONTRACT_STATUS = (
    CONTRACT_STATUS_ACTIVE,
    CONTRACT_STATUS_EXPIRED,
    CONTRACT_STATUS_RENEWED,
    CONTRACT_STATUS_CANCELED,
)
# 视为有效、参与租期冲突校验的合同状态
VALID_CONTRACT_STATUS = (CONTRACT_STATUS_ACTIVE, CONTRACT_STATUS_RENEWED)

# 续租协商状态（合同卡片展示用）
RENEWAL_STATUS_PENDING_LANDLORD = '待房东处理'
RENEWAL_STATUS_PENDING_TENANT = '待租客确认'
RENEWAL_STATUS_RENEWED = '已续租'
RENEWAL_STATUS_CANCELED = '已取消'
RENEWAL_STATUS = (
    RENEWAL_STATUS_PENDING_LANDLORD,
    RENEWAL_STATUS_PENDING_TENANT,
    RENEWAL_STATUS_RENEWED,
    RENEWAL_STATUS_CANCELED,
)
# 已结束的续租协商，不能再处理
RENEWAL_FINISHED_STATUS = (RENEWAL_STATUS_RENEWED, RENEWAL_STATUS_CANCELED)
# 进行中的续租协商，同一合同只能有一个
RENEWAL_OPEN_STATUS = (RENEWAL_STATUS_PENDING_LANDLORD, RENEWAL_STATUS_PENDING_TENANT)

# 续租协商动作（用于处理留痕）
RENEWAL_ACTION_CREATE = '发起续租'
RENEWAL_ACTION_ACCEPT = '接受'
RENEWAL_ACTION_COUNTER = '还价'
RENEWAL_ACTION_REJECT = '拒绝'
RENEWAL_ACTION_CONFIRM = '确认接受'
RENEWAL_ACTION_TENANT_CANCEL = '取消续租'
