ERROR_CODES = {
    'PROPERTY_NOT_FOUND': 'PROPERTY_NOT_FOUND',
    'BOOKING_CONFLICT': 'BOOKING_CONFLICT',
    'REPAIR_INVALID': 'REPAIR_INVALID',
    'CONTRACT_NOT_FOUND': 'CONTRACT_NOT_FOUND',
    'RENEWAL_NOT_FOUND': 'RENEWAL_NOT_FOUND',
    'RENEWAL_FORBIDDEN': 'RENEWAL_FORBIDDEN',
    'RENEWAL_STATE_INVALID': 'RENEWAL_STATE_INVALID',
    'RENEWAL_DUPLICATE': 'RENEWAL_DUPLICATE',
    'RENEWAL_CONFLICT': 'RENEWAL_CONFLICT',
    'RENEWAL_INVALID_INPUT': 'RENEWAL_INVALID_INPUT',
}

ERROR_MESSAGES = {
    'PROPERTY_NOT_FOUND': '房源不存在',
    'BOOKING_CONFLICT': '该时间段已有预约',
    'REPAIR_INVALID': '报修信息不完整',
    'CONTRACT_NOT_FOUND': '合同不存在',
    'RENEWAL_NOT_FOUND': '续租协商不存在',
    'RENEWAL_FORBIDDEN': '当前角色无权处理该续租协商',
    'RENEWAL_STATE_INVALID': '续租协商已结束，不能再更改',
    'RENEWAL_DUPLICATE': '该合同已有进行中的续租协商',
    'RENEWAL_CONFLICT': '新租期与同一房源的其他有效合同重叠',
    'RENEWAL_INVALID_INPUT': '续租信息填写有误',
}
