ERROR_CODES = {
    'PROPERTY_NOT_FOUND': 'PROPERTY_NOT_FOUND',
    'BOOKING_CONFLICT': 'BOOKING_CONFLICT',
    'REPAIR_INVALID': 'REPAIR_INVALID',
    # 续租协商
    'CONTRACT_NOT_FOUND': 'CONTRACT_NOT_FOUND',
    'RENEWAL_NOT_FOUND': 'RENEWAL_NOT_FOUND',
    'INVALID_ROLE': 'INVALID_ROLE',
    'CONTRACT_ALREADY_RENEWED': 'CONTRACT_ALREADY_RENEWED',
    'CONTRACT_NOT_RENEWABLE': 'CONTRACT_NOT_RENEWABLE',
    'ACTIVE_RENEWAL_EXISTS': 'ACTIVE_RENEWAL_EXISTS',
    'INVALID_RENEWAL_TERM': 'INVALID_RENEWAL_TERM',
    'INVALID_RENEWAL_ACTION': 'INVALID_RENEWAL_ACTION',
    'RENEWAL_STATUS_FINISHED': 'RENEWAL_STATUS_FINISHED',
    'RENEWAL_STATUS_MISMATCH': 'RENEWAL_STATUS_MISMATCH',
    'COUNTER_RENT_REQUIRED': 'COUNTER_RENT_REQUIRED',
    'RENEWAL_CONFLICT': 'RENEWAL_CONFLICT',
}

ERROR_MESSAGES = {
    'CONTRACT_NOT_FOUND': '合同不存在',
    'RENEWAL_NOT_FOUND': '续租协商不存在',
    'INVALID_ROLE': '角色不合法，仅支持房东或租客',
    'CONTRACT_ALREADY_RENEWED': '已续租的合同不再更改',
    'CONTRACT_NOT_RENEWABLE': '当前合同状态不可发起续租',
    'ACTIVE_RENEWAL_EXISTS': '该合同已有进行中的续租协商，请处理完后再发起',
    'INVALID_RENEWAL_TERM': '新租期不合法：结束日期须晚于开始日期，且开始日期不能早于当前合同到期日',
    'INVALID_RENEWAL_ACTION': '续租处理动作不合法',
    'RENEWAL_STATUS_FINISHED': '续租协商已结束，不能再处理',
    'RENEWAL_STATUS_MISMATCH': '当前状态不允许该操作',
    'COUNTER_RENT_REQUIRED': '还价时必须填写新的期望月租',
    'RENEWAL_CONFLICT': '新租期与同一房源的其他有效合同存在冲突，请确认后再处理',
}
